name: APT tests
on: [push]
jobs:
  test-apt:
    runs-on: ubuntu-latest
    steps:
      - name: List files in /etc/apt/
        run: ls -la /etc/apt/
      - name: List files in /etc/apt/sources.list.d/
        run: ls -la /etc/apt/sources.list.d/
      - name: Print contents of /etc/apt/sources.list
        run: cat /etc/apt/sources.list
      - name: Add deb-src
        run: sed -i 's/^Types: deb$/Types: deb deb-src/' /etc/apt/sources.list.d/ubuntu.sources
      - name: Print updated contents of /etc/apt/sources.list
        run: cat /etc/apt/sources.list

